### ISSUE TITLE
Fix the Card Display!! 

### ISSUE THREAD

**Issue by Vidhanvyrs** [Vidhanvyrs/WeatherApp#1]
Checkout the CONTRIBUTING.md file if you are new here
here you can fork and run the app by using 
->npm i
->npm start
Enter the Location 
then click get updates you will get to see the error that is been displayed here in the ss
Opinion: check these components out I think the error resides in either of them 
WeatherApp/blob/master/src/MainCard.js
WeatherApp/blob/master/src/Card.js
Current behavior:

![Screenshot (165)](https://github.com/Vidhanvyrs/WeatherApp/assets/94836010/7c93a27c-456d-41d0-bc0a-b8473632693b)

Expected Behavior:
the cards are getting out and of the div as well as the way they are displayed are not correct i want one to be displayed at one time and when the > button is clicked the next info card should displayed not the copy of the whole array of weather cards

**Comment by conorvenus** [comment]
I will give this one a go.
