### ISSUE TITLE
Prop drilling and context issue

### ISSUE THREAD

**Issue by nueladeyemi1** [Vidhanvyrs/WeatherApp#11]
Hello Vidhanvyrs,

I noticed after you use createContext, props were still passed around the components. I can help refractor the code in order to remove the prop drillings.

Also, few classes in css need to be clean up in order to make the app responsive.

Assign these issues to me, thank you.

**Comment by Vidhanvyrs** [comment]
Yes you are right the prop drilling is still there 
Ok @nueladeyemi1 assigning the task to you
