### ISSUE TITLE
Update the Project's README

### ISSUE THREAD

**Issue by Vidhanvyrs** [Vidhanvyrs/WeatherApp#2]
Provide the readme file with some great technical incentives about the project and its working so that the user can easily use it

**Comment by ShanieshaJ** [comment]
I will give this documentation for a README.md a try

**Comment by Vidhanvyrs** [comment]
Sure let me assign you the task

**Comment by ShanieshaJ** [comment]
Okay, I have added 5 sections to the README.md for the weather app so far:

# Weather App

This project is built using HTML, CSS and React framework. It allows users to get real-time weather information for their current location or any other location they search for. The app fetches weather from a reliable weather API and presents it in a user-friendly and visually appealing manner.

## Features

**Real-time Weather Data**: The app provides up-to-date weather information for any location worldwide.

**Search Functionality**: Users can search for weather information for a specific location by entering its city name, and displaying the coordinates (latitude and longitude).

**Weather Details**: The app presents detailed weather information, including temperature, humidity, wind speed, and weather condition.

**Weather Forecast**: Presents the weather forecast for the next few days, including high and low temperatures, enabling users to plan their travel activities accordingly.

**Climate Change**: Informs users to learn about climate change and steps to take action.

## API Key

This weather app uses OpenWeatherMap API to fetch weather data. To set up and use the API key:

1. Visit [OpenWeatherMap](https://openweathermap.org/) website and create an account.
2. To obtain an API key after creating an account. This key will be required to make API calls.
3. Copy and then paste the API key into the project code.
4. Save the changes.

## Live preview

You can view this project by [clicking here](https://weather-app-two-peach.vercel.app/)

## Contributing

Contributions to this project are welcome. If you would like to contribute to the project, please follow these steps here:

1. Fork the WeatherApp repository and then clone the project.
2. Create a new branch for a feature or fix a bug.
3. Make necessary changes in your new branch (The one you created).
4. Test your changes thoroughly.
5. Save your changes before committing and pushing them into Github (**Most important**).
6. Submit a pull request to the main repository.

[Contribution guidelines for this project](CONTRIBUTING.md)


> [!NOTE]
> If you have a suggestion that would make this better, please fork the repository and create a pull request. You can also report an issue with the label tag. Provide detailed information about the problem you faced, steps to reproduce it, and any relevant screenshots if possible.
