### ISSUE TITLE
Displaying of the day name

### ISSUE THREAD

**Issue by Vidhanvyrs** [Vidhanvyrs/WeatherApp#6]
Current Behavior:
As you can see when the weather details are updated upon entering the location we found all the 4 cards displaying the info but they lack the info about which day are they showing the weather details of 
Expected Behavior:
to make the card display the day also so that it would be easier for the user to choose the day according to the weather details provided
![image](https://github.com/Vidhanvyrs/WeatherApp/assets/94836010/bfb23ee8-ea5e-49a6-bfe3-087961f7cbd5)

**Comment by 0m3ga13** [comment]
if I understood, you wanted to add the date in your main Card. 
use the date method in javascript 
```javascript
const currentDate = new Date();
 const options = { weekday: "long", year: "numeric", month: "long", day: "numeric" }; // you can change it 
 const formattedDate = currentDate.toLocaleDateString(undefined, options); // Get today's date with

//your code

 return (
            <div className="card" key={index}>
              <p>{formattedDate}</p>
              
```

**Comment by Vidhanvyrs** [comment]
okay so i should add this in my card component naa! but the data also should be of the day ie the card should display the data of the current day not of the other day so will this code prevail in that too

**Comment by 0m3ga13** [comment]
> okay so i should add this in my card component naa! but the data also should be of the day ie the card should display the data of the current day not of the other day so will this code prevail in that too

you mean each card represents a different day?

**Comment by Vidhanvyrs** [comment]
okay so let me elaborate what the issue is 
see for now the cards are properly displaying the weather data that is the temperature whether it is raining or no stuff like that 
but it lacks the name of the day that is whether that data that is been displayed here is of monday,  tuesday or wednesday like that 
hope this makes the issue clear

**Comment by Vidhanvyrs** [comment]
> > okay so i should add this in my card component naa! but the data also should be of the day ie the card should display the data of the current day not of the other day so will this code prevail in that too
> 
> you mean each card represents a different day?

Yes I think that is needed as the data is for different days too

**Comment by 0m3ga13** [comment]
okay my bad you can easily retrieve the date from the data
same way as earlier just change this

```javascript 
const date = new Date(data.dt * 1000); // Convert Unix timestamp to milliseconds
          const options = { weekday: "long", year: "numeric", month: "long", day: "numeric" };
          const formattedDate = date.toLocaleDateString(undefined, options);
          
          ```

**Comment by Vidhanvyrs** [comment]
> okay my bad you can easily retrieve the date from the data same way as earlier just change this
> 
> ```js
> const date = new Date(data.dt * 1000); // Convert Unix timestamp to milliseconds
>           const options = { weekday: "long", year: "numeric", month: "long", day: "numeric" };
>           const formattedDate = date.toLocaleDateString(undefined, options);
>           
>           ```
> ```

ok sure i added this code but now it is only displaying sunday and monday for three times
 instead i think it should give sunday monday tuesday wednesday 
 I think the error is coming from the api data

 
![Screenshot 2023-08-13 204829](https://github.com/Vidhanvyrs/WeatherApp/assets/94836010/2edd9655-26f1-42d4-b2e6-b7a39a8e4a83)

**Comment by MZ-AD** [comment]
I am willing to work on this, please assign this issue to me :)

**Comment by Vidhanvyrs** [comment]
hey @Moeez905 you are more than welcome to contribute in this project as you can see @0m3ga13 has helped a lot in this issue so you can follow up the work and the latest bug that we are getting which i have commented

**Comment by Vidhanvyrs** [comment]
> > okay my bad you can easily retrieve the date from the data same way as earlier just change this
> > ```js
> > const date = new Date(data.dt * 1000); // Convert Unix timestamp to milliseconds
> >           const options = { weekday: "long", year: "numeric", month: "long", day: "numeric" };
> >           const formattedDate = date.toLocaleDateString(undefined, options);
> >           
> >           ```
> > ```
> 
> ok sure i added this code but now it is only displaying sunday and monday for three times instead i think it should give sunday monday tuesday wednesday I think the error is coming from the api data
> 
> ![Screenshot 2023-08-13 204829](https://user-images.githubusercontent.com/94836010/260311693-2edd9655-26f1-42d4-b2e6-b7a39a8e4a83.png)

this one

**Comment by 0m3ga13** [comment]
@Vidhanvyrs  I think the issue is in the API call, the timestamps are not days 
```
forecastData = [
  { dt: 1691949600, /* other fields */ },
  { dt: 1691960400, /* other fields */ },
  { dt: 1691971200, /* other fields */ },
  { dt: 1691982000, /* other fields */ }
];
``` 

try to use daily forcast api instead
https://openweathermap.org/forecast16 and let me know

**Comment by Vidhanvyrs** [comment]
ya i was skeptical about it sure will work on this !!
I think we can close this issue, until @Moeez905 have anything to contribute then i'll wait till tomorrow and then would do

**Comment by Bolaji06** [comment]
Hi everyone 🤗 If the issue has not been resolved, I can work on this. Did something similar to my previous weather app project. Thanks in advance.

**Comment by Vidhanvyrs** [comment]
I have done some changes so the dayname is actually now available but still the days are not in correct order that is form sunday to saturday 
@Bolaji06 you have been assigned with this too thanx for the help 
Let me know if there is any doubt

**Comment by Bolaji06** [comment]
Alright am still tryna get the full picture of of the problem. I can see that the day names are been displayed now.

**Comment by Vidhanvyrs** [comment]
yeah so the daynames are displayed but you can see that monday wednesday and friday these are missing 
as @0m3ga13 suggested to use https://openweathermap.org/forecast16 then we can get all the seven days data so can you be able to do that

**Comment by Bolaji06** [comment]
> yeah so the daynames are displayed but you can see that monday wednesday and friday these are missing as @0m3ga13 suggested to use https://openweathermap.org/forecast16 then we can get all the seven days data so can you be able to do that

Let me see what I can come up with

**Comment by Vidhanvyrs** [comment]
sure thing

**Comment by MZ-AD** [comment]
> hey @Moeez905 you are more than welcome to contribute in this project as you can see @0m3ga13 has helped a lot in this issue so you can follow up the work and the latest bug that we are getting which i have commented

Thanks! I'm on it! and up-to date with progress of this issue

**Comment by Bolaji06** [comment]
Have been going through the API response before writing any line of code. I may be wrong, if I am I need someone to correct me. OpenWeather API is not giving us the full 7 days weather forecast to work with I tried converting the timestamp they provided all the time timestamp are not up to 7 days, even the dt_txt properties is not up to 7 days. If there is anything am missing please kindly notify me ASAP.

**Comment by MZ-AD** [comment]
@Bolaji06 API is showing forecast for all 7 days / week. There's nothing wrong with API.
in app.js this line >     const forecastData = weatherResponse.data.list.slice(0, 4);
caused data splicing and website were dispalying forecast for 4 days obviously as said in code clearly.

**Comment by MZ-AD** [comment]
I've pushed some changes, its now showing all 7 days but days name aren't in sequence, "dayIndex" needs some work

**Comment by Vidhanvyrs** [comment]
I'll see to the issue with the array of weekdays myself 
Really Appreciated your help guys 🙇‍♂️
Happy Coding 🚀🎧
